#!/bin/bash

# Import common functions
if ! source "../common/common.sh" >/dev/null 2>&1; then
    printf '%s\n' "Error: Could not import common functions" >&2
    exit 1
fi

if ! check_modelsim; then
    err "Could not find ModelSim tools in current PATH"
    exit 1
fi

ip_dir="../../src/ip"
rtl_dir="../../src/rtl"
lib_dir="../lib"
tb_dir="./"

# Work directory
work="work"

# Exit on errors while we're compiling
set -e

# Remove existing ModelSim work library
vdel -lib "${work}" -all

vlib "${work}"
vmap work "${work}"

# Map in the Xilinx simulation libraries
vmap UNISIM "${lib_dir}/2024.1/modelsim_16.1/UNISIM"
vmap UNIMACRO "${lib_dir}/2024.1/modelsim_16.1/UNIMACRO"

# Packages need to be compiled in before the rest of the testbench
vlog -work "${work}" -sv "${tb_dir}/uart_pkg.v"
vlog -work "${work}" -sv "${tb_dir}/uart_rx_tb.v"

# Compile DUT
vcom -work "${work}" -2008 "${ip_dir}/baseline/fifo_sync.vhd"

vcom -lint -work "${work}" -2008 "${rtl_dir}/baseline/skid_buffer.vhd"
vcom -lint -work "${work}" -2008 "${rtl_dir}/baseline/clk_rst.vhd"
vcom -lint -work "${work}" -2008 "${rtl_dir}/baseline/baud_rate_gen.vhd"
vcom -lint -work "${work}" -2008 "${rtl_dir}/baseline/uart_rx.vhd"
vcom -lint -work "${work}" -2008 "${rtl_dir}/baseline/uart_tx.vhd"
vcom -lint -work "${work}" -2008 "${rtl_dir}/baseline/uart.vhd"

# Done compiling, so turn this back on
set +e

