#!/bin/bash

# Runs a simulation for the AXI4-Lite interface and register array. The
# AXI4-lite bridge to control and interface registers is small, but requires
# extensive testing since it will likely be reused many times and the AXI
# interface is one that has lots of edge cases that need to be handled properly
# or it will lead to hanging the bus in hardware.

# Common testbench setup script
if ! source "../common/sim.conf"; then
    printf '%s\n' "Error: Could not setup simulation environment" >&2
    exit 1
fi
print_sim_setup

# Exit on errors while we're compiling 
set -e 

rtl_dir="${baseline_src_dir}/rtl"
tb_dir="./"

rtl_dir="${baseline_src_dir}/rtl"

# Work directory
work="work"
# Remove existing ModelSim work library
if [[ -d "${work}" ]]; then
    rm -rf "${work}"
fi

vlib "${work}"
vmap work "${work}"

vcom -lint -work "${work}" -2008 "${rtl_dir}/axi4l_regs.vhd"

vlog -work "${work}" -sv "${tb_dir}/axi4l_regs_tb.sv"

# Done compiling, so turn this back on
set +e

